spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jaws
    password: jaws
    url: jdbc:postgresql://localhost:5432/jaws
  application:
    name: upload_jaws_server
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
jaws-server:
  server-url: server-url/images/
